name: Deploy Website to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
          cache-dependency-path: 'website-FinanceFlow/yarn.lock'

      - name: Install dependencies
        run: yarn install
        working-directory: ./website-FinanceFlow

      - name: Build
        run: yarn build
        working-directory: ./website-FinanceFlow

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website-FinanceFlow/dist
